spring:
  cloud:
    config:
      server:
        native:
#          search-locations: classpath:/shared
          search-locations: file:/Users/yangjiandong/workspace/ssh/ssh-config
  profiles:
     active: native

server:
  port: 8888

security:
  user:
#    password: ${CONFIG_SERVICE_PASSWORD}
    password: 123
